## An simple model to predict:
### 1. ability of each student
### 2. attributes of each problem
### 3. whether she/he will make a correct choice.

In [1]:
### import libraries
import numpy as np
import tensorflow as tf
import time
import xlrd, csv
import pandas as pd

In [2]:
### open the chemistry exam record 
workbook = xlrd.open_workbook('eng_20180305.xlsx')
names = workbook.sheet_names()

xlsx = pd.ExcelFile('eng_20180305.xlsx')
df1 = xlsx.parse(names[0], header=None)
df2 = xlsx.parse(names[1], header=None)
df3 = xlsx.parse(names[2], header=None)

In [3]:
df3

0   1   2   3   4   5   6   7   8   9  ...  71  72  73  74  75  76  \
0   192355   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
1   192224   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
2   192347   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
3   192348   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
4   192371   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
5   191845   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
6   192020   0   1   0   0   0   0   0   1   0 ...   0   1   1   0   0   0   
7   192366   1   0   0   0   0   1   0   0   0 ...   0   0   0   1   0   0   
8   191933   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
9   191900   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
10  192048   1   0   0   0   0   0   1   0   0 ...   0   1   0   1   0   0   
11  192353   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
12  192001   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
13  192082   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
14  192369   1   0   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
15  192364   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
16  192254   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
17  192041   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
18  191991   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
19  191972   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
20  192358   0   0   1   0   0   0   0   1   0 ...   0   1   0   1   0   0   
21  191987   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
22  191958   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
23  192357   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
24  191892   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
25  191984   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
26  192045   0   1   0   0   0   0   1   0   0 ...   0   1   1   0   0   0   
27  191929   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
28  192264   0   1   0   0   0   0   0   1   0 ...   0   0   1   0   0   0   
29  192339   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
30  192315   1   0   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
31  192139   0   1   0   0   0   1   0   0   0 ...   0   1   0   1   0   0   
32  191928   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
33  192113   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
34  192090   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
35  191952   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
36  191999   0   1   0   0   0   0   0   1   0 ...   0   1   1   0   0   0   
37  180016   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
38  191833   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
39  192332   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
40  192118   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
41  191888   1   0   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
42  192032   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
43  191974   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
44  192177   1   0   0   0   0   1   0   0   0 ...   0   1   0   1   0   0   
45  192331   1   0   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
46  191349   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   
47    標準答案   0   1   0   0   0   0   0   1   0 ...   0   1   0   1   0   0   

    77  78  79  80  
0    0   0   0   1  
1    0   0   0   1  
2    0   0   0   1  
3    0   0   0   1  
4    0   0   0   1  
5    0   0   0   1  
6    0   0   0   1  
7    0   0   0   

In [4]:
df2_ = df2.dropna(axis = 1)

In [5]:
df2_.columns = range(21)

In [6]:
df2_.loc[47][1:21]

1     B
2     D
3     B
4     C
5     C
6     A
7     D
8     B
9     A
10    B
11    B
12    D
13    C
14    A
15    A
16    A
17    C
18    D
19    B
20    D
Name: 47, dtype: object

In [7]:
### process the data 
df2_ = df2.dropna(axis = 1)
df2_.columns = range(21)

scores = []
for i_ in range(0,47):
    score = ((df2_.loc[i_][1:21]==df2_.loc[47][1:21]))
    scores.append(score)

scores = (np.array(scores)).astype(np.float)

In [8]:
### "scores" indicates how each student scores on each problem
###  (3 students, 10 problems)
pd.DataFrame(scores)

0    1    2    3    4    5    6    7    8    9    10   11   12   13   14  \
0   1.0  1.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0   
1   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0   
2   1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0   
3   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0   
4   1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
5   1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0   
6   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0   
7   0.0  0.0  1.0  1.0  0.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0   
8   1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
9   1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0   
10  0.0  0.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  1.0  1.0   
11  1.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
12  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
13  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
14  0.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  1.0   
15  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  0.0  1.0   
16  1.0  1.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0   
17  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  1.0  0.0  1.0  1.0  1.0   
18  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0  0.0  1.0   
19  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0   
20  0.0  1.0  0.0  0.0  1.0  0.0  1.0  1.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0   
21  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0   
22  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
23  1.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0   
24  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  1.0  1.0  1.0   
25  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0   
26  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  0.0  1.0   
27  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
28  1.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0   
29  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
30  0.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0   
31  1.0  0.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0   
32  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
33  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  1.0   
34  1.0  1.0  1.0  1.0  0.0  0.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0   
35  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0   
36  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
37  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
38  1.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0   
39  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
40  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0   
41  0.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  0.0  0.0   
42  1.0  1.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
43  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0   
44  0.0  0.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0   
45  0.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  1.0  1.0  1.0   
46  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  0.0  1.0  0.0  1.0  1.0  1.0   

     15   16   17   18   19  
0   1.0  0.0  1.0  1.0  1.0  
1   1.0  1.0  1.0  1.0  1.0  
2   0.0  1.0  1.0  1.0  1.

In [9]:
'''
these parameters means: 
number of students
number of problems
number of latent factors
ratio of missing values and complete data
number of missing values
hyper parameters 1, to restrict the sum of elements in each problem to be one
hyper parameters 2, to restrict elements in each problem to be less than one  
'''
n_student = 47
n_prob = 20
n_latent = 6
ratio = 0.1
n_zeros = int(n_student*n_prob* ratio)
lamb1 = 0.1
lamb2 = 5.  

In [10]:
# proj_mat defines positions to drop a ratio of data randomly
# (optional)
proj_mat = np.ones(n_student*n_prob)
proj_mat[:n_zeros] = 0
np.random.shuffle( proj_mat )
proj_mat = proj_mat.reshape([n_student, n_prob])
test_mat = np.ones([n_student, n_prob]) - proj_mat

In [11]:
proj_mat.shape

(47, 20)

In [13]:
#test_mat

In [1]:
import numpy as np
import tensorflow as tf
import time
import xlrd, csv
import pandas as pd
workbook = xlrd.open_workbook('eng_20180305.xlsx')
names = workbook.sheet_names()

xlsx = pd.ExcelFile('eng_20180305.xlsx')
df1 = xlsx.parse(names[0], header=None)
df2 = xlsx.parse(names[1], header=None)
df3 = xlsx.parse(names[2], header=None)
df2_ = df2.dropna(axis = 1)
df2_.columns = range(21)
df2_ = df2.dropna(axis = 1)
df2_.columns = range(21)

scores = []
for i_ in range(0,47):
    score = ((df2_.loc[i_][1:21]==df2_.loc[47][1:21]))
    scores.append(score)

scores = (np.array(scores)).astype(np.float)
n_student = 47
n_prob = 20
n_latent = 6
ratio = 0.1
n_zeros = int(n_student*n_prob* ratio)
lamb1 = 0.00001
lamb2 = 5.  
proj_mat = np.ones(n_student*n_prob)
proj_mat[:n_zeros] = 0
np.random.shuffle( proj_mat )
proj_mat = proj_mat.reshape([n_student, n_prob])
test_mat = np.ones([n_student, n_prob]) - proj_mat

### Use tensorflow(TF) to construct model:

In [2]:
sess = tf.Session()

In [3]:
class recomend:
    def __init__(self, n_student, n_prob, n_latent, ratio, lamb1, lamb2):
        self.ones = tf.constant(np.ones([n_student,n_prob]),
                                dtype=tf.float32)
        self.n_student = n_student
        self.n_prob = n_prob
        #self.lamb = lamb
        self.scores = tf.placeholder(dtype = tf.float32 ,
                                     shape = [n_student, n_prob])
        self.proj_ = tf.placeholder(dtype = tf.float32 ,
                                     shape = [n_student, n_prob])
        self.s_ = tf.get_variable("student",
                                     shape=[n_student, n_latent])
        self.s_bias = tf.get_variable("student_bias",
                                     shape=[n_student, 1])
        self.p_ = tf.get_variable("problem", shape=[n_prob, n_latent])
        self.p_bias = tf.get_variable("problem_bias", shape=[n_prob, 1])
        
#        self.predict =  tf.sigmoid(
#            tf.matmul(self.s_, tf.transpose(self.p_) ) + 
#            tf.tile(self.s_bias, [1, n_prob]) +
#            tf.transpose(tf.tile(self.p_bias, [1, n_student]))
#                                  )

        self.predict =  tf.sigmoid(
            tf.matmul(self.s_, tf.transpose(self.p_) ) + 
            tf.tile(self.s_bias, [1, n_prob])    )
        
#        self.predict =  tf.sigmoid(
#            tf.matmul(self.s_, tf.transpose(self.p_) )     )


#        self.loss_0 = tf.reduce_sum(tf.mul(-( 
#                                 self.scores*tf.log((3./4.)*self.predict + (1./4.)*self.ones  ) 
#                   + 3*(self.ones-self.scores)*tf.log((1./4.)*self.ones - (1./4.)* self.predict  +1e-6)   
#                                        ),self.proj_  ))/(n_student*n_prob* (1-ratio) )

#        self.loss_0 = tf.reduce_sum(tf.mul(-(
#          tf.mul(  self.scores, tf.log(self.predict + 1e-7  ) )    
#      + 3*tf.mul( (self.ones-self.scores),tf.log((1./3.)*(self.ones - self.predict)  +1e-7) )   
#                                             ),self.proj_  ))/(n_student*n_prob* (1-ratio) )
    
        self.loss_0 = tf.reduce_sum(tf.mul(-(
          tf.mul(  self.scores, tf.log(self.predict + 1e-6  ) )    
        + tf.mul( (self.ones-self.scores),tf.log(self.ones - self.predict  +1e-6) )   
                                             ),self.proj_  ))/(n_student*n_prob* (1-ratio) )
    
    
        self.loss_1 = lamb1 * (tf.reduce_sum(tf.square(self.p_) ) 
                              + tf.reduce_sum(tf.square(self.s_) )  )  #/((n_student+n_prob)*n_latent)
#        loss_0 = tf.reduce_sum(tf.square(self.predict-self.scores) )/(n_student*n_prob* (1-ratio) )
#        loss_1 = lamb1 * tf.reduce_sum(tf.square(tf.reduce_sum(self.p_, reduction_indices = 1) - self.ones) )
#        loss_2 = lamb2 * tf.reduce_sum(tf.pow(self.p_, 8) )/(n_student*n_prob* (1-ratio) )
#        self.loss = loss_0 + loss_1 + loss_2
        self.loss = self.loss_0 + self.loss_1

In [4]:
model = recomend(n_student, n_prob, n_latent, ratio, lamb1, lamb2)

In [5]:
#train_op = tf.train.GradientDescentOptimizer(1e-3).minimize(model.loss)
train_op = tf.train.AdamOptimizer(1e-4).minimize(model.loss)

In [6]:
sess.run(tf.initialize_all_variables() )

In [7]:
## start training:
delta = 10
loss_old = 1e3
steps = 0
t0 = 0
while loss_old > 23e-4:
    sess.run(train_op, feed_dict = {model.scores:scores,
                                    model.proj_: proj_mat })
    loss_0 = sess.run(model.loss_0, feed_dict = {model.scores:scores,
                                    model.proj_: proj_mat })
    loss_1 = sess.run(model.loss_1, feed_dict = {model.scores:scores,
                                    model.proj_: proj_mat })
#    loss_new = sess.run(model.loss, feed_dict = {model.scores:scores,
#                                    model.proj_: proj_mat })
    loss_new = loss_0 + loss_1
#    delta = loss_old - loss_new
    loss_old = loss_new
    steps +=1
    if steps%5000 ==0:
        t1 = time.time() - t0
        print(steps, loss_0, loss_1, t1)
        t0 = time.time()

(5000, 0.33535126, 0.00011362384, 1521045674.305626)
(10000, 0.19653061, 0.00027120087, 7.177963972091675)
(15000, 0.10191252, 0.00049933291, 7.1649720668792725)
(20000, 0.048238073, 0.00079186651, 7.187780857086182)
(25000, 0.020378446, 0.0011200886, 7.178605079650879)
(30000, 0.0079168137, 0.0014272069, 7.160017967224121)
(35000, 0.0028976253, 0.0017219717, 7.169911861419678)
(40000, 0.0010856534, 0.0019457241, 7.236469984054565)
(45000, 0.00051718694, 0.0020584809, 7.316339015960693)
(50000, 0.00037410916, 0.0020592441, 7.3143720626831055)
(55000, 0.00034267307, 0.002030686, 7.144145965576172)
(60000, 0.00033822833, 0.0019965607, 7.199632883071899)


In [8]:
## final loss  and   delta
print(loss_new, delta)

(0.0022999849, 10)


### Let's check the results:

In [20]:
#print(sess.run(model.s_))

In [21]:
model_s_result = sess.run(model.s_)
np.max(model_s_result)

1.2183449e-35

In [48]:
print(sess.run(model.p_))

[[ 0.58920366]
 [-0.14931335]
 [-0.08959205]
 [-0.12398325]
 [ 0.11247037]
 [ 0.08131763]
 [-0.11876544]
 [-0.14667065]
 [-0.17851865]
 [ 0.31801909]]


In [22]:
print(sess.run(model.s_bias) )

[[-0.38195994]
 [ 0.83473742]
 [-0.22291008]
 [ 0.44970974]
 [ 0.20601271]
 [ 0.72971833]
 [-0.28396329]
 [-1.22805178]
 [ 1.47496676]
 [ 0.88680929]
 [-2.20079517]
 [ 0.49502876]
 [ 1.59226334]
 [ 1.63328457]
 [-0.27842823]
 [-0.5516029 ]
 [-0.02909459]
 [ 0.10446824]
 [ 0.12373965]
 [ 0.24261487]
 [-1.33673108]
 [ 0.85993874]
 [ 1.42287338]
 [ 0.64396906]
 [-0.27852923]
 [ 0.37451819]
 [-0.75064504]
 [ 1.67785025]
 [-1.32199669]
 [ 1.42710423]
 [-0.67782253]
 [-0.75130147]
 [ 0.82685721]
 [ 0.01960127]
 [-0.84978426]
 [ 0.75275779]
 [-0.04212089]
 [ 1.51650536]
 [ 0.46773177]
 [ 1.49798965]
 [ 1.3163408 ]
 [-0.48198211]
 [ 0.40389618]
 [ 1.57893407]
 [-1.86084378]
 [-0.23939994]
 [ 0.12222748]]


In [23]:
print(sess.run(model.p_bias))

[[ 0.41657346]
 [ 0.81423414]
 [ 1.54764521]
 [-1.1188184 ]
 [ 1.73351574]
 [-0.14143038]
 [ 2.64904332]
 [-0.34406841]
 [ 0.46323016]
 [-1.42823339]
 [-0.31930372]
 [-0.18602544]
 [ 0.37714282]
 [-0.31317341]
 [ 0.29649702]
 [-0.5005089 ]
 [ 1.10799086]
 [ 1.8821559 ]
 [ 0.75280339]
 [ 2.10366726]]


### counting wrong predicts

In [8]:
predict = sess.run(model.predict)
n_wrong = int(np.sum(np.square((np.sign(predict-0.25)+1)/2  - scores)*test_mat))
print(str(n_wrong)+' wrong predictions within '+ str(n_zeros) +' test samples' )

21 wrong predictions within 94 test samples


In [9]:
73/94.

0.776595744680851

### All predict results 

In [55]:
print(predict)

[[ 0.68387806  0.87448925  0.81742489  0.88892168  0.88406408  0.66685808
   0.85936093  0.87845802  0.89053136  0.51143295]
 [ 0.91387326  0.96102738  0.94209385  0.96626365  0.96804839  0.88693517
   0.95636934  0.96241969  0.96601206  0.81996822]
 [ 0.67637992  0.90385598  0.85465145  0.91434568  0.90138036  0.70873845
   0.89048922  0.90689397  0.9175083   0.53343326]]


In [56]:
print(scores)

[[ 1.  1.  1.  1.  1.  0.  1.  1.  1.  0.]
 [ 1.  1.  0.  1.  1.  1.  1.  1.  1.  1.]
 [ 0.  1.  1.  1.  1.  1.  1.  1.  1.  1.]]


In [17]:
ans_p = sess.run(model.p_, feed_dict = {model.scores:scores, model.proj_: proj_mat })
ans_s = sess.run(model.s_, feed_dict = {model.scores:scores, model.proj_: proj_mat })

In [18]:
print(np.max(ans_p))
print(np.max(ans_s))
print(np.max(p_mat))
print(np.max(s_mat))

1.16439
19.0288
0.536235179729
99


### The matrix "scores" corresponds to the actual scores students get,  each row corresponds to one student

In [19]:
scores

array([[ 52.67019706,  77.35301135,  59.15939095, ...,  59.93032837,
          0.        ,   0.        ],
       [ 47.74065807,  37.63227162,  35.40073239, ...,  54.0015399 ,
         55.28178138,  42.90616783],
       [ 46.38629337,  41.00573029,   0.        , ...,  40.05709955,
         45.1835761 ,  32.13017566],
       ..., 
       [ 32.62758583,  37.35290522,   0.        , ...,  41.88571342,
         34.00440983,  45.5966174 ],
       [ 44.59803368,  47.51215155,  42.46353872, ...,  35.88972598,
          0.        ,  19.03881936],
       [ 64.49604241,  41.26206108,  55.01551282, ...,  49.74749856,
         66.05305759,  57.30576901]])

### The matrix "predict" corresponds to the scores predicted by the model

In [20]:
predict = sess.run(model.predict, feed_dict = {model.scores:scores, model.proj_: proj_mat })
predict 

array([[ 50.31025696,  51.0971756 ,  50.85494995, ...,  49.55835342,
          0.        ,   0.        ],
       [ 42.00656891,  42.65892029,  42.45944595, ...,  41.37759399,
         41.76087952,  41.22695923],
       [ 51.43185425,  52.22583389,   0.        , ...,  50.65138626,
         51.12961197,  50.46997452],
       ..., 
       [ 31.10415268,  31.58787346,   0.        , ...,  30.63759232,
         30.92169189,  30.52473068],
       [ 41.2207756 ,  41.86265564,  41.66644669, ...,  40.59862518,
          0.        ,  40.44944   ],
       [ 60.9866066 ,  61.92451477,  61.64091492, ...,  60.0588913 ,
         60.62866211,  59.8453331 ]], dtype=float32)

In [21]:
p_mat[0]

array([ 0.2280732 ,  0.17640353,  0.06800562,  0.20650069,  0.32101697])

In [22]:
ans_p[0]

array([ 1.02335465,  1.11626089, -1.13355446,  1.12117815, -1.12711513], dtype=float32)